# flickr30k_val_karpathy, 1014 datapoints
task_factory: "contrastive_multitext"
n_texts_per_image: 5
dataset:
    dataset_factory: "clip_benchmark_contrastive_multitext"
    dataset_name: "flickr30k"
    dataset_split: "val"
