# imagenet living things classes only (410 of 1000 classes), ts (trainsmall) set
task_factory: "zeroshot_classification"
clip_zs_template: "openai_imagenet_template"
dataset:
    dataset_factory: "imagenet1k"
    dataset_name: "living_things"
    dataset_split: "trainsmall"
