# imagenet other (non-living-things) classes only (590 of 1000 classes), ts (trainsmall) set
task_factory: "zeroshot_classification"
clip_zs_template: "none"
dataset:
    dataset_factory: "imagenet1k"
    dataset_name: "not_living_things"
    dataset_split: "trainsmall"
