# imagenet 1k (all labels), ts (trainsmall) set, 50k images
task_factory: "zeroshot_classification"
clip_zs_template: "openai_imagenet_template"
dataset:
    dataset_factory: "imagenet1k"
    dataset_name: "default"
    dataset_split: "trainsmall"
    max_datapoints: 500
