# iNaturalist 2021 val set, english class names
task_factory: "zeroshot_classification"
clip_zs_template: "openai_imagenet_template"
dataset:
    dataset_factory: "inat21"
    dataset_name: "inat21-en"
    dataset_split: "val"
