# iNaturalist 2021 traindev (new) set, english class names, 100k images
task_factory: "zeroshot_classification"
clip_zs_template: "none"
dataset:
    dataset_factory: "inat21"
    dataset_name: "inat21-en"
    dataset_split: "traindev"
