task_keys:
    - "imgv2_1k_test_temp"
    - "imgv2_1k_test_notemp"
    - "imgr_200_test_temp"
    - "imgr_200_test_notemp"
    - "objn_1k_test_notemp"
    - "objn_1k_test_temp"
    - "imgsketch_1k_test_temp"
    - "imgsketch_1k_test_notemp"
    - "imga_200_test_temp"
    - "imga_200_test_notemp"
#    - "domn_345_test_temp"
#    - "domn_345_test_notemp"
#    - "imgo_200_test_temp"
#    - "imgo_200_test_notemp"
