task_keys:
    - "cubobj_train_ccrop_itemp"
    - "cubobj_train_ccrop_notemp"
    - "cubobj_train_squash_notemp"
    - "cubobjbox_train_ccrop_itemp"
    - "cubobjbox_train_ccrop_notemp"
    - "cubobjbox_train_squash_notemp"
    - "cubobj_test_ccrop_itemp"
    - "cubobj_test_ccrop_notemp"
    - "cubobj_test_squash_notemp"
    - "cubobjbox_test_ccrop_itemp"
    - "cubobjbox_test_ccrop_notemp"
    - "cubobjbox_test_squash_notemp"
