task_keys:
    - "imgn_1k_ts"
    - "imgn_lt_ts"
    - "imgn_ot_ts"
    - "imgn_1k_ts_notemp"
    - "imgn_lt_ts_notemp"
    - "imgn_ot_ts_notemp"
    - "imgn_1k_val"
    - "imgn_lt_val"
    - "imgn_ot_val"
    - "imgn_1k_val_notemp"
    - "imgn_lt_val_notemp"
    - "imgn_ot_val_notemp"
    - "imga_200_test_temp"
    - "imga_200_test_notemp"
    - "imgr_200_test_temp"
    - "imgr_200_test_notemp"
    - "imgo_200_test_temp"
    - "imgo_200_test_notemp"
    - "imgsketch_1k_test_temp"
    - "imgsketch_1k_test_notemp"
    - "imgv2_1k_test_temp"
    - "imgv2_1k_test_notemp"
    - "objn_1k_test_notemp"
    - "objn_1k_test_temp"
    - "cubobj_train_ccrop_itemp"
    - "cubobj_train_ccrop_notemp"
    - "cubobj_train_squash_notemp"
    - "cubobjbox_train_ccrop_itemp"
    - "cubobjbox_train_ccrop_notemp"
    - "cubobjbox_train_squash_notemp"
    - "cubobj_test_ccrop_itemp"
    - "cubobj_test_ccrop_notemp"
    - "cubobj_test_squash_notemp"
    - "cubobjbox_test_ccrop_itemp"
    - "cubobjbox_test_ccrop_notemp"
    - "cubobjbox_test_squash_notemp"
    - "inat19_tdev"
    - "inat19lat_tdev"
    - "inat19_tdev_itemp"
    - "inat19lat_tdev_itemp"
    - "inat19_val"
    - "inat19lat_val"
    - "inat19_val_itemp"
    - "inat19lat_val_itemp"
    - "inat21_tdev"
    - "inat21lat_tdev"
    - "inat21_tdev_itemp"
    - "inat21lat_tdev_itemp"
    - "inat21_val"
    - "inat21lat_val"
    - "inat21_val_itemp"
    - "inat21lat_val_itemp"
    - "rarespecies_train_com_inettemp"
    - "rarespecies_train_com_none"
    - "rarespecies_train_sci_inettemp"
    - "rarespecies_train_sci_none"
    - "rarespecies_train_scicom_inettemp"
    - "rarespecies_train_scicom_none"
    - "rarespecies_train_tax_inettemp"
    - "rarespecies_train_tax_none"
    - "rarespecies_train_taxcom_inettemp"
    - "rarespecies_train_taxcom_none"
    - "coco_karp_test"
    - "flickr30k_test"
    - "xm3600_test"
